# Generated by Django 4.2.7 on 2023-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_api", "0002_note_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="user_name",
            field=models.CharField(max_length=50),
        ),
    ]
