# Generated by Django 4.2.7 on 2023-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="user_name",
            field=models.CharField(default=True, max_length=50),
        ),
    ]
